# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# https://docs.travis-ci.com/user/database-setup/#PostgreSQL
before_script:
- psql -U postgres -c "create database topjava;"
- psql -U postgres -c "create user 'user' with password 'password';"
- psql -U postgres -c  "grant all privileges on database topjava to 'user';"

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - HW04

addons:
  postgresql: "10"

# https://stackoverflow.com/a/49852690/548473:
services:
  - postgresql

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
#notifications:
#  email: false